# Generated by Django 5.1.4 on 2024-12-28 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chatroom_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'ordering': ['-created_at'], 'verbose_name': 'Chat Room', 'verbose_name_plural': 'Chat Rooms'},
        ),
    ]
